#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/charts/tree/master/charts/common/values.yaml
#

image:
  repository: monica
  pullPolicy: IfNotPresent
  tag: 2.19.1-apache

strategy:
  type: Recreate

env:
  # See the Monica documentation for all available options for environment variables: https://raw.githubusercontent.com/monicahq/monica/master/.env.example
  # APP_ENV: production
  # Generate a different APP_KEY with `pwgen -s 32 1`
  APP_KEY: Er9eYH1nwcwItLHyPHj5iVcJqZXeWvnv
  # APP_URL: https://crm.k8s-at-home.com
  DB_HOST: monica-mariadb
  DB_DATABASE: monica
  DB_USERNAME: monica
  DB_PASSWORD: monicapass

service:
  port:
    port: 80

ingress:
  enabled: false

persistence:
  config:
    enabled: true
    emptyDir: false
    mountPath: /var/www/html/storage
    storageClass: nfs-client

# Enabled mariadb
# ... for more options see https://github.com/bitnami/charts/tree/master/bitnami/mariadb
mariadb:
  enabled: true
  architecture: standalone
  auth:
    database: monica
    username: monica
    password: monicapass
    rootPassword: monicarootpass
  primary:
    persistence:
      enabled: false
      storageClass: nfs-client

