apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: taiga-cert
  namespace: default
spec:
  dnsNames:
    - taiga.dentropydaemon.net
  secretName: taiga-cert-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
