apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: openproject-http-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: openproject-http-cert
    solvers:
    - http01:
       ingress:
         class: traefik
