apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trilium-cert
  namespace: default
spec:
  dnsNames:
    - trilium.dentropydaemon.net
  secretName: trilium-cert-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
