apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trilium-notes-cert
  namespace: cert-manager-test
spec:
  dnsNames:
    - trilium.${YOUR_DOMAIN_NAME}
  secretName: trilium-notes-cert-tls
  issuerRef:
    name: test-selfsigned