apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: owncloud-cert
  namespace: default
spec:
  dnsNames:
    - owncloud.dentropydaemon.net
  secretName: nextcloud-cert-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer