apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openproject-pgdata
spec:
  volumeName: openproject-pgdata
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
