apiVersion: v1
kind: PersistentVolume
metadata:
  name: openproject-pgdata
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 127.0.0.1
    path: "/mnt/nfsdir/openproject/pgdata"
