apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openproject-data
spec:
  volumeName: openproject-data
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
